// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using licencjatApi.Data;

#nullable disable

namespace licencjatApi.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20250315100454_aaa")]
    partial class aaa
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("licencjat_api.Models.Criterion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsStimulant")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Criteria");
                });

            modelBuilder.Entity("licencjat_api.Models.HostelCriterionValue", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CriterionId")
                        .HasColumnType("int");

                    b.Property<int>("MountainHostelId")
                        .HasColumnType("int");

                    b.Property<decimal>("Value")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("MountainHostelId");

                    b.HasIndex("CriterionId", "MountainHostelId")
                        .IsUnique();

                    b.ToTable("HostelCriterionValues", t =>
                        {
                            t.HasCheckConstraint("CK_HostelCriterionValue_Value_NonNegative", "Value >= 0");
                        });
                });

            modelBuilder.Entity("licencjat_api.Models.MountainHostel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("MountainHostels");
                });

            modelBuilder.Entity("licencjat_api.Models.Parameter", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Key")
                        .IsUnique();

                    b.ToTable("Parameters");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Nazwa metody używanej przez program",
                            Key = "MethodName",
                            Value = ""
                        });
                });

            modelBuilder.Entity("licencjat_api.Models.HostelCriterionValue", b =>
                {
                    b.HasOne("licencjat_api.Models.Criterion", "Criterion")
                        .WithMany("HostelCriterionValues")
                        .HasForeignKey("CriterionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("licencjat_api.Models.MountainHostel", "MountainHostel")
                        .WithMany("HostelCriterionValues")
                        .HasForeignKey("MountainHostelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Criterion");

                    b.Navigation("MountainHostel");
                });

            modelBuilder.Entity("licencjat_api.Models.Criterion", b =>
                {
                    b.Navigation("HostelCriterionValues");
                });

            modelBuilder.Entity("licencjat_api.Models.MountainHostel", b =>
                {
                    b.Navigation("HostelCriterionValues");
                });
#pragma warning restore 612, 618
        }
    }
}
